<?php

namespace Database\Seeders;

use App\Models\Agent;
use App\Models\City;
use App\Models\District;
use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\PropertyFacility;
use App\Models\Category;
use App\Models\PropertyType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DummyPropertySeeder extends Seeder
{
    public function run(): void
    {
        $sleman   = City::where('slug', 'sleman')->first();
        $bantul   = City::where('slug', 'bantul')->first();
        $jogja    = City::where('slug', 'kota-yogyakarta')->first();
        $klp      = City::where('slug', 'kulon-progo')->first();
        $gk       = City::where('slug', 'gunungkidul')->first();

        $depok    = District::where('slug', 'depok-sleman')->first();
        $mlati    = District::where('slug', 'mlati-sleman')->first();
        $godean   = District::where('slug', 'godean-sleman')->first();
        $ngaglik  = District::where('slug', 'ngaglik-sleman')->first();
        $kasihan  = District::where('slug', 'kasihan-bantul')->first();
        $piyungan = District::where('slug', 'piyungan-bantul')->first();
        $wonosari = District::where('slug', 'wonosari-gunungkidul')->first();
        $patuk    = District::where('slug', 'patuk-gunungkidul')->first();
        $wates    = District::where('slug', 'wates-kulon-progo')->first();
        $sentolo  = District::where('slug', 'sentolo-kulon-progo')->first();
        $gondokusuman = District::where('slug', 'gondokusuman-kota-yogyakarta')->first();
        $umbulharjo  = District::where('slug', 'umbulharjo-kota-yogyakarta')->first();
        $mergangsan  = District::where('slug', 'mergangsan-kota-yogyakarta')->first();
        $berbah      = District::where('slug', 'berbah-sleman')->first();
        $prambanan   = District::where('slug', 'prambanan-sleman')->first();
        $seweon      = District::where('slug', 'sewon-bantul')->first();
        $pandak      = District::where('slug', 'pandak-bantul')->first();
        $banguntapan = District::where('slug', 'banguntapan-bantul')->first();
        $imogiri     = District::where('slug', 'imogiri-bantul')->first();
        $playen      = District::where('slug', 'playen-gunungkidul')->first();
        $temon       = District::where('slug', 'temon-kulon-progo')->first();
        $pengasih    = District::where('slug', 'pengasih-kulon-progo')->first();

        $catRes    = Category::where('slug', 'residential')->first();
        $catVilla  = Category::where('slug', 'luxury-villa')->first();
        $catApt    = Category::where('slug', 'apartment')->first();
        $catLand   = Category::where('slug', 'land')->first();
        $catCom    = Category::where('slug', 'commercial')->first();
        $catOffice = Category::where('slug', 'office-space')->first();

        $typeRumah = PropertyType::where('slug', 'rumah')->first();
        $typeVilla = PropertyType::where('slug', 'villa')->first();
        $typeApt   = PropertyType::where('slug', 'apartemen')->first();
        $typeTanah = PropertyType::where('slug', 'tanah')->first();
        $typeRuko  = PropertyType::where('slug', 'ruko')->first();
        $typeGudang= PropertyType::where('slug', 'gudang')->first();
        $typeKantor= PropertyType::where('slug', 'kantor')->first();
        $typeHotel = PropertyType::where('slug', 'hotel')->first();
        $typeCom   = PropertyType::where('slug', 'commercial-type')->first();

        $agents = Agent::where('is_active', true)->get();

        $properties = [
            // ─── Gudang di Sleman ───────────────────────────────────────────────
            [
                'title'            => 'Gudang Gudang Modern Sleman',
                'slug'             => 'gudang-modern-sleman',
                'property_id_code' => 'PROP-D01',
                'description'      => 'Gudang modern berlokasi di kawasan industri Sleman. Luas bangunan 800m², lantai beton, listrik 10.000W, akses truk. Cocok untuk pergudangan, distribusi, atau manufaktur ringan.',
                'short_description'=> 'Gudang modern 800m², listrik besar, akses truk di Sleman.',
                'transaction_type' => 'dijual',
                'price'            => 5500000000,
                'land_area'        => 1200, 'building_area' => 800,
                'bedrooms'         => null, 'bathrooms' => 2, 'garage' => null, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2018,
                'electric_power'   => '10000W',
                'address'          => 'Jl. Raya Solo, Ngaglik, Sleman',
                'latitude'         => -7.7450, 'longitude' => 110.4010,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeGudang?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $ngaglik?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                'facilities'       => ['Listrik 10000W', 'Air PDAM', 'Akses Truk', 'Parkir Luas', 'Keamanan'],
                'images'           => [
                    'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                    'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
                    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
                    'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80',
                ],
            ],

            // ─── Kantor di Kota Yogyakarta ─────────────────────────────────────
            [
                'title'            => 'Kantor Siap Pakai Malioboro',
                'slug'             => 'kantor-siap-pakai-malioboro',
                'property_id_code' => 'PROP-D02',
                'description'      => 'Ruang kantor siap pakai di kawasan bisnis Malioboro. Fasilitas lengkap: AC, internet fiber, resepsionis, ruang rapat. Lokasi sangat strategis, dekat hotel dan transportasi umum.',
                'short_description'=> 'Kantor furnished di Malioboro, internet fiber, lokasi prima.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 15000000,
                'land_area'        => null, 'building_area' => 120,
                'bedrooms'         => null, 'bathrooms' => 2, 'garage' => null, 'floors' => 1,
                'certificate'      => 'SHMSRS',
                'year_built'       => 2020,
                'electric_power'   => '3500W',
                'address'          => 'Jl. Malioboro No. 50, Gondokusuman, Kota Yogyakarta',
                'latitude'         => -7.7928, 'longitude' => 110.3659,
                'status'           => 'published', 'is_featured' => true,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catOffice?->id,
                'property_type_id' => $typeKantor?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => $gondokusuman?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                'facilities'       => ['AC', 'Internet Fiber', 'Resepsionis', 'Ruang Rapat', 'CCTV', 'Lift'],
                'images'           => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                    'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
                    'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&q=80',
                    'https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&q=80',
                ],
            ],

            // ─── Hotel di Gunungkidul ──────────────────────────────────────────
            [
                'title'            => 'Hotel Boutique Wonosari',
                'slug'             => 'hotel-boutique-wonosari',
                'property_id_code' => 'PROP-D03',
                'description'      => 'Hotel boutique 20 kamar di Wonosari, Gunungkidul. Cocok untuk investasi pariwisata dekat destinasi wisata alam seperti Gua Pindul, Jomblang, dan pantai selatan.',
                'short_description'=> 'Hotel 20 kamar di Wonosari, dekat wisata alam Gunungkidul.',
                'transaction_type' => 'dijual',
                'price'            => 12000000000,
                'land_area'        => 800, 'building_area' => 1200,
                'bedrooms'         => 20,  'bathrooms' => 22, 'garage' => 10, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2019,
                'electric_power'   => '15000W',
                'address'          => 'Jl. Raya Wonosari, Wonosari, Gunungkidul',
                'latitude'         => -7.9667, 'longitude' => 110.6000,
                'status'           => 'published', 'is_featured' => true,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeHotel?->id,
                'city_id'          => $gk?->id,
                'district_id'      => $wonosari?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
                'facilities'       => ['Kolam Renang', 'Restoran', 'WiFi', 'Parkir', 'Ruang Meeting', 'Laundry'],
                'images'           => [
                    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
                    'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
                    'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
                ],
            ],

            // ─── Commercial/Kos di Kulon Progo ─────────────────────────────────
            [
                'title'            => 'Kos Eksklusif Dekat Bandara Kulon Progo',
                'slug'             => 'kos-eksklusif-bandara-kulon-progo',
                'property_id_code' => 'PROP-D04',
                'description'      => 'Bangunan kos-kosan 15 kamar di dekat Bandara Internasional Yogyakarta. Setiap kamar full furnished dengan AC, kasur, lemari, dan kamar mandi dalam. Investasi menguntungkan.',
                'short_description'=> 'Kos 15 kamar full furnished, dekat Bandara YIA, investasi pasti.',
                'transaction_type' => 'dijual',
                'price'            => 3200000000,
                'land_area'        => 300, 'building_area' => 450,
                'bedrooms'         => 15,  'bathrooms' => 15, 'garage' => 5, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2023,
                'electric_power'   => '5500W',
                'address'          => 'Jl. Wates, Pengasih, Kulon Progo',
                'latitude'         => -7.8167, 'longitude' => 110.2333,
                'status'           => 'featured', 'is_featured' => true,
                'agent_id'         => $agents[4]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $klp?->id,
                'district_id'      => $pengasih?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
                'facilities'       => ['Full Furnished', 'AC', 'Kamar Mandi Dalam', 'WiFi', 'Parkir', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
                    'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80',
                    'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
                ],
            ],

            // ─── Disewa: Ruko di Bantul ───────────────────────────────────────
            [
                'title'            => 'Ruko Sewa Harian Bantul City',
                'slug'             => 'ruko-sewa-harian-bantul-city',
                'property_id_code' => 'PROP-D05',
                'description'      => 'Ruko 2 lantai siap sewa di pusat kota Bantul. Cocok untuk toko, klinik, atau kantor cabang. Lokasi di jalan utama, sangat ramai.',
                'short_description'=> 'Ruko 2 lantai sewa di pusat Bantul, jalan utama ramai.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 8000000,
                'land_area'        => 80, 'building_area' => 160,
                'bedrooms'         => null, 'bathrooms' => 2, 'garage' => 1, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2021,
                'electric_power'   => '3500W',
                'address'          => 'Jl. Jendral Sudirman, Bantul',
                'latitude'         => -7.8889, 'longitude' => 110.3333,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeRuko?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $kasihan?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                'facilities'       => ['Listrik 3 Phase', 'Air PDAM', 'Parkir Depan', 'Akses 24 Jam'],
                'images'           => [
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
                ],
            ],

            // ─── Sold: Rumah di Kota Yogyakarta ────────────────────────────────
            [
                'title'            => 'Rumah Mewah Jogja Permai',
                'slug'             => 'rumah-mewah-jogja-permai',
                'property_id_code' => 'PROP-D06',
                'description'      => 'Rumah mewah di perumahan elite Jogja Permai, Mergangsan. Desain arsitektur modern tropis, taman luas, garasi 2 mobil. Sudah terjual.',
                'short_description'=> 'Rumah mewah modern tropis, garasi 2 mobil, Jogja Permai.',
                'transaction_type' => 'dijual',
                'price'            => 4500000000,
                'land_area'        => 250, 'building_area' => 200,
                'bedrooms'         => 4,   'bathrooms' => 3, 'garage' => 2, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2021,
                'electric_power'   => '3500W',
                'address'          => 'Jogja Permai, Mergangsan, Kota Yogyakarta',
                'latitude'         => -7.8056, 'longitude' => 110.3700,
                'status'           => 'sold', 'is_featured' => false,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => $mergangsan?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
                'facilities'       => ['Garasi 2 Mobil', 'Taman', 'Air Sumur', 'Keamanan 24 Jam', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566753376-12c8ab7c5a38?w=800&q=80',
                ],
            ],

            // ─── Rented: Apartemen di Sleman ───────────────────────────────────
            [
                'title'            => 'Apartemen Condoview Sleman Disewakan',
                'slug'             => 'apartemen-condoview-sleman-disewakan',
                'property_id_code' => 'PROP-D07',
                'description'      => 'Apartemen modern condoview di Sleman. Fasilitas lengkap: kolam renang, gym, minimarket. Lokasi dekat UGM dan kampus lainnya.',
                'short_description'=> 'Apartemen condoview Sleman, fasilitas lengkap, dekat kampus.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 3500000,
                'land_area'        => null, 'building_area' => 45,
                'bedrooms'         => 1,   'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHMSRS',
                'year_built'       => 2022,
                'electric_power'   => '1300W',
                'address'          => 'Jl. Kaliurang, Depok, Sleman',
                'latitude'         => -7.7700, 'longitude' => 110.3900,
                'status'           => 'rented', 'is_featured' => false,
                'agent_id'         => $agents[3]->id,
                'category_id'      => $catApt?->id,
                'property_type_id' => $typeApt?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $depok?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                'facilities'       => ['Kolam Renang', 'Gym', 'Minimarket', 'Lift', 'Security', 'WiFi'],
                'images'           => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80',
                    'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
                    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
                ],
            ],

            // ─── Tanah di Gunungkidul ──────────────────────────────────────────
            [
                'title'            => 'Tanah Kavling Perbukitan Patuk',
                'slug'             => 'tanah-kavling-perbukitan-patuk',
                'property_id_code' => 'PROP-D08',
                'description'      => 'Tanah kavling di perbukitan Patuk, Gunungkidul. View Gunung Merapi yang spektakuler. Cocok untuk villa atau hunian alam. Udara sejuk dan asri.',
                'short_description'=> 'Tanah kavling view Merapi di Patuk, udara sejuk dan asri.',
                'transaction_type' => 'dijual',
                'price'            => 450000000,
                'land_area'        => 200, 'building_area' => null,
                'bedrooms'         => null, 'bathrooms' => null, 'garage' => null, 'floors' => null,
                'certificate'      => 'SHM',
                'year_built'       => null,
                'electric_power'   => null,
                'address'          => 'Patuk, Gunungkidul',
                'latitude'         => -7.8167, 'longitude' => 110.5667,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catLand?->id,
                'property_type_id' => $typeTanah?->id,
                'city_id'          => $gk?->id,
                'district_id'      => $patuk?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                'facilities'       => ['View Merapi', 'Akses Jalan', 'Udara Sejuk'],
                'images'           => [
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                    'https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=800&q=80',
                    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
                    'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
                ],
            ],

            // ─── Rumah disewa di Kulon Progo ───────────────────────────────────
            [
                'title'            => 'Rumah Minimalis Sewa Bulanan Wates',
                'slug'             => 'rumah-minimalis-sewa-wates',
                'property_id_code' => 'PROP-D09',
                'description'      => 'Rumah minimalis 2 lantai untuk disewa bulanan di Wates, Kulon Progo. Cocok untuk keluarga kecil. Dekat pasar, sekolah, dan puskesmas.',
                'short_description'=> 'Rumah minimalis sewa bulanan di Wates, dekat fasilitas umum.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 5000000,
                'land_area'        => 100, 'building_area' => 70,
                'bedrooms'         => 2,   'bathrooms' => 1, 'garage' => 1, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2020,
                'electric_power'   => '1300W',
                'address'          => 'Jl. Nasional III, Wates, Kulon Progo',
                'latitude'         => -7.8553, 'longitude' => 110.1620,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[4]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $klp?->id,
                'district_id'      => $wates?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
                'facilities'       => ['Carport', 'Taman Kecil', 'Air PDAM', 'Listrik PLN'],
                'images'           => [
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
                    'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
                ],
            ],

            // ─── Rumah di Bantul ───────────────────────────────────────────────
            [
                'title'            => 'Rumah Joglo Tradisional Imogiri',
                'slug'             => 'rumah-joglo-tradisional-imogiri',
                'property_id_code' => 'PROP-D10',
                'description'      => 'Rumah joglo asli Jawa dengan ukiran kayu jati di Imogiri, Bantul. Suasana pedesaan yang tenang, cocok untuk hunian atau homestay. Dekat makam raja-raja Mataram.',
                'short_description'=> 'Rumah joglo kayu jati, suasana pedesaan tenang di Imogiri.',
                'transaction_type' => 'dijual',
                'price'            => 2800000000,
                'land_area'        => 300, 'building_area' => 180,
                'bedrooms'         => 3,   'bathrooms' => 2, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 1998,
                'electric_power'   => '2200W',
                'address'          => 'Imogiri, Bantul',
                'latitude'         => -7.9333, 'longitude' => 110.3833,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $imogiri?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                'facilities'       => ['Ukiran Kayu Jati', 'Taman Luas', 'Sumur Bor', 'Pendopo'],
                'images'           => [
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80',
                    'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&q=80',
                ],
            ],

            // ─── Villa disewa di Gunungkidul ───────────────────────────────────
            [
                'title'            => 'Vila Pemandangan Laut Gunungkidul',
                'slug'             => 'vila-pemandangan-laut-gunungkidul',
                'property_id_code' => 'PROP-D11',
                'description'      => 'Vila tepi laut di kawasan pantai selatan Gunungkidul. Pemandangan Samudera Hindia yang menakjubkan. Tersedia untuk sewa mingguan/bulanan.',
                'short_description'=> 'Vila tepi laut view Samudera Hindia, sewa mingguan/bulanan.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 12000000,
                'land_area'        => 400, 'building_area' => 250,
                'bedrooms'         => 3,   'bathrooms' => 3, 'garage' => 2, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2022,
                'electric_power'   => '3500W',
                'address'          => 'Playen, Gunungkidul',
                'latitude'         => -7.9833, 'longitude' => 110.5500,
                'status'           => 'published', 'is_featured' => true,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catVilla?->id,
                'property_type_id' => $typeVilla?->id,
                'city_id'          => $gk?->id,
                'district_id'      => $playen?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
                'facilities'       => ['View Laut', 'Taman', 'Dapur Luar', 'WiFi', 'Parkir', 'Gazebo'],
                'images'           => [
                    'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
                    'https://images.unsplash.com/photo-1591825729269-caeb344f6df2?w=800&q=80',
                    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
                ],
            ],

            // ─── Rumah di Kulon Progo ──────────────────────────────────────────
            [
                'title'            => 'Rumah Cluster Griya Sentolo',
                'slug'             => 'rumah-cluster-griya-sentolo',
                'property_id_code' => 'PROP-D12',
                'description'      => 'Rumah cluster baru di Sentolo, Kulon Progo. Harga terjangkau, desain modern minimalis. Cocok untuk keluarga muda yang mencari hunian nyaman.',
                'short_description'=> 'Rumah cluster minimalis, harga terjangkau di Sentolo.',
                'transaction_type' => 'dijual',
                'price'            => 650000000,
                'land_area'        => 70, 'building_area' => 54,
                'bedrooms'         => 2,   'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2025,
                'electric_power'   => '1300W',
                'address'          => 'Griya Sentolo, Sentolo, Kulon Progo',
                'latitude'         => -7.8333, 'longitude' => 110.2167,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[4]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $klp?->id,
                'district_id'      => $sentolo?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
                'facilities'       => ['One Gate System', 'Taman', 'Carport', 'Air PDAM', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80',
                    'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80',
                    'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
                ],
            ],

            // ─── Kantor disewa di Sleman ───────────────────────────────────────
            [
                'title'            => 'Ruang Kantor Co-Working Space Sleman',
                'slug'             => 'ruang-kantor-co-working-sleman',
                'property_id_code' => 'PROP-D13',
                'description'      => 'Ruang co-working space fleksibel di Sleman. Tersedia hot desk, dedicated desk, dan private office. Fasilitas lengkap, komunitas kreatif.',
                'short_description'=> 'Co-working space fleksibel di Sleman, fasilitas lengkap.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 2000000,
                'land_area'        => null, 'building_area' => 30,
                'bedrooms'         => null, 'bathrooms' => 1, 'garage' => null, 'floors' => 1,
                'certificate'      => null,
                'year_built'       => 2024,
                'electric_power'   => '2200W',
                'address'          => 'Jl. Affandi, Depok, Sleman',
                'latitude'         => -7.7750, 'longitude' => 110.3850,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catOffice?->id,
                'property_type_id' => $typeKantor?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $depok?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                'facilities'       => ['WiFi Cepat', 'AC', 'Ruang Rapat', 'Pantry', 'Printer', 'Parkir'],
                'images'           => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                    'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&q=80',
                    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
                    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&q=80',
                ],
            ],

            // ─── Rumah di Bantul (published) ───────────────────────────────────
            [
                'title'            => 'Rumah Modern Minimalis Piyungan',
                'slug'             => 'rumah-modern-minimalis-piyungan',
                'property_id_code' => 'PROP-D14',
                'description'      => 'Rumah modern minimalis di Piyungan, Bantul. Lokasi strategis dekat akses jalan raya Jogja-Wonosari. Lingkungan perumahan baru yang asri.',
                'short_description'=> 'Rumah modern minimalis di Piyungan, akses strategis.',
                'transaction_type' => 'dijual',
                'price'            => 950000000,
                'land_area'        => 105, 'building_area' => 75,
                'bedrooms'         => 3,   'bathrooms' => 2, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2024,
                'electric_power'   => '1300W',
                'address'          => 'Piyungan, Bantul',
                'latitude'         => -7.8167, 'longitude' => 110.4500,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $piyungan?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
                'facilities'       => ['Carport', 'Taman', 'Water Heater', 'Air PDAM', 'One Gate System'],
                'images'           => [
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&q=80',
                ],
            ],

            // ─── Commercial: Toko di Bantul (sold) ─────────────────────────────
            [
                'title'            => 'Toko Bangunan Sudah Terjual',
                'slug'             => 'toko-bangunan-sudah-terjual',
                'property_id_code' => 'PROP-D15',
                'description'      => 'Toko bangunan di kawasan ramai Bantul. Sudah terjual. Listing ini hanya untuk referensi.',
                'short_description'=> 'Toko bangunan di Bantul, sudah terjual.',
                'transaction_type' => 'dijual',
                'price'            => 1800000000,
                'land_area'        => 150, 'building_area' => 120,
                'bedrooms'         => null, 'bathrooms' => 1, 'garage' => null, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2015,
                'electric_power'   => '3500W',
                'address'          => 'Jl. Bantul, Sewon, Bantul',
                'latitude'         => -7.8333, 'longitude' => 110.3667,
                'status'           => 'sold', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeCom?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $seweon?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                'facilities'       => ['Parkir Luas', 'Ruang Display', 'Gudang'],
                'images'           => [
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
                    'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
                ],
            ],

            // ─── Tanah di Bantul (disewa) ─────────────────────────────────────
            [
                'title'            => 'Tanah Pertanian Sewa Tahunan Pandak',
                'slug'             => 'tanah-pertanian-sewa-pandak',
                'property_id_code' => 'PROP-D16',
                'description'      => 'Tanah pertanian seluas 500m² untuk disewa tahunan di Pandak, Bantul. Cocok untuk urban farming, green house, atau kebun organik.',
                'short_description'=> 'Tanah pertanian 500m² sewa tahunan di Pandak, cocok farming.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 2500000,
                'land_area'        => 500, 'building_area' => null,
                'bedrooms'         => null, 'bathrooms' => null, 'garage' => null, 'floors' => null,
                'certificate'      => null,
                'year_built'       => null,
                'electric_power'   => null,
                'address'          => 'Pandak, Bantul',
                'latitude'         => -7.8333, 'longitude' => 110.3000,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catLand?->id,
                'property_type_id' => $typeTanah?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $pandak?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                'facilities'       => ['Air Irigasi', 'Akses Jalan', 'Tanah Subur'],
                'images'           => [
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
                    'https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=800&q=80',
                    'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80',
                ],
            ],

            // ─── Rumah di Sleman (featured, berbagai harga) ────────────────────
            [
                'title'            => 'Rumah Eksklusif Kaliurang Hills',
                'slug'             => 'rumah-eksklusif-kaliurang-hills',
                'property_id_code' => 'PROP-D17',
                'description'      => 'Rumah eksklusif di kawasan Kaliurang dengan view Gunung Merapi. Desain arsitektur modern mewah, kolam renang pribadi, taman tropis. Lingkungan perumahan premium.',
                'short_description'=> 'Rumah eksklusif view Merapi, kolam renang, Kaliurang.',
                'transaction_type' => 'dijual',
                'price'            => 15000000000,
                'land_area'        => 600, 'building_area' => 450,
                'bedrooms'         => 5,   'bathrooms' => 4, 'garage' => 3, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2023,
                'electric_power'   => '7700W',
                'address'          => 'Kaliurang, Pakem, Sleman',
                'latitude'         => -7.6780, 'longitude' => 110.4100,
                'status'           => 'featured', 'is_featured' => true,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
                'facilities'       => ['Kolam Renang', 'View Merapi', 'Smart Home', 'Gym Pribadi', 'Garasi 3 Mobil', 'Taman Tropis', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566753376-12c8ab7c5a38?w=800&q=80',
                ],
            ],

            // ─── Rumah disewa di Bantul ────────────────────────────────────────
            [
                'title'            => 'Rumah Type 36 Sewa Harian Banguntapan',
                'slug'             => 'rumah-type-36-sewa-banguntapan',
                'property_id_code' => 'PROP-D18',
                'description'      => 'Rumah type 36 untuk disewa harian di Banguntapan, Bantul. Dekat Universitas Ahmad Dahlan dan RS PKU Muhammadiyah. Cocok untuk mahasiswa atau pasien rawat inap.',
                'short_description'=> 'Rumah type 36 sewa harian, dekat kampus dan rumah sakit.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 3000000,
                'land_area'        => 72, 'building_area' => 36,
                'bedrooms'         => 2,   'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2018,
                'electric_power'   => '1300W',
                'address'          => 'Banguntapan, Bantul',
                'latitude'         => -7.8167, 'longitude' => 110.4167,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $banguntapan?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
                'facilities'       => ['Carport', 'Dapur', 'Air PDAM', 'Listrik PLN'],
                'images'           => [
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
                    'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
                ],
            ],

            // ─── Ruko di Gunungkidul ───────────────────────────────────────────
            [
                'title'            => 'Ruko 2 Lantai Wonosari Center',
                'slug'             => 'ruko-2-lantai-wonosari-center',
                'property_id_code' => 'PROP-D19',
                'description'      => 'Ruko strategis 2 lantai di pusat Wonosari. Cocok untuk apotek, klinik, atau toko elektronik. Lalu lintas tinggi, banyak penduduk.',
                'short_description'=> 'Ruko 2 lantai pusat Wonosari, lokasi ramai.',
                'transaction_type' => 'dijual',
                'price'            => 1200000000,
                'land_area'        => 80, 'building_area' => 120,
                'bedrooms'         => null, 'bathrooms' => 2, 'garage' => null, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2017,
                'electric_power'   => '3500W',
                'address'          => 'Jl. Raya Wonosari, Wonosari, Gunungkidul',
                'latitude'         => -7.9667, 'longitude' => 110.6000,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeRuko?->id,
                'city_id'          => $gk?->id,
                'district_id'      => $wonosari?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                'facilities'       => ['Listrik 3 Phase', 'Air PDAM', 'Ruang Display', 'Gudang'],
                'images'           => [
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
                ],
            ],

            // ─── Rumah di Kota Yogyakarta (disewa) ────────────────────────────
            [
                'title'            => 'Rumah Tinggal Sewa Bulanan Umbulharjo',
                'slug'             => 'rumah-tinggal-sewa-umbulharjo',
                'property_id_code' => 'PROP-D20',
                'description'      => 'Rumah tinggal nyaman untuk disewa bulanan di Umbulharjo, Kota Yogyakarta. Dekat Taman Sari dan Keraton. Lingkungan budaya yang kental.',
                'short_description'=> 'Rumah sewa bulanan dekat Taman Sari, lingkungan budaya.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 8000000,
                'land_area'        => 150, 'building_area' => 100,
                'bedrooms'         => 3,   'bathrooms' => 2, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2005,
                'electric_power'   => '2200W',
                'address'          => 'Umbulharjo, Kota Yogyakarta',
                'latitude'         => -7.8100, 'longitude' => 110.3550,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => $umbulharjo?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
                'facilities'       => ['Taman', 'Dapur', 'Ruang Tamu Luas', 'Air PDAM', 'Listrik PLN'],
                'images'           => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80',
                ],
            ],

            // ─── Gudang di Kulon Progo ─────────────────────────────────────────
            [
                'title'            => 'Gudang Sewa Dekat Bandara YIA',
                'slug'             => 'gudang-sewa-dekat-bandara-yia',
                'property_id_code' => 'PROP-D21',
                'description'      => 'Gudang seluas 500m² untuk disewa di dekat Bandara Internasional Yogyakarta. Akses truk mudah, cocok untuk logistik atau distribusi.',
                'short_description'=> 'Gudang 500m² sewa dekat Bandara YIA, akses logistik.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 20000000,
                'land_area'        => 600, 'building_area' => 500,
                'bedrooms'         => null, 'bathrooms' => 1, 'garage' => null, 'floors' => 1,
                'certificate'      => null,
                'year_built'       => 2020,
                'electric_power'   => '5500W',
                'address'          => 'Temon, Kulon Progo',
                'latitude'         => -7.8167, 'longitude' => 110.1833,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[4]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeGudang?->id,
                'city_id'          => $klp?->id,
                'district_id'      => $temon?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                'facilities'       => ['Akses Truk', 'Listrik 5500W', 'Air Sumur', 'Parkir Luas'],
                'images'           => [
                    'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                    'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
                    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
                    'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80',
                ],
            ],

            // ─── Tanah di Sleman (berbagai harga) ──────────────────────────────
            [
                'title'            => 'Tanah Kavling Komersial Berbah',
                'slug'             => 'tanah-kavling-komersial-berbah',
                'property_id_code' => 'PROP-D22',
                'description'      => 'Tanah kavling komersial di Berbah, Sleman. Strategis untuk ruko, kantor, atau gudang. Sudah ada IMB dan sertifikat.',
                'short_description'=> 'Tanah komersial strategis di Berbah, siap bangun.',
                'transaction_type' => 'dijual',
                'price'            => 1500000000,
                'land_area'        => 250, 'building_area' => null,
                'bedrooms'         => null, 'bathrooms' => null, 'garage' => null, 'floors' => null,
                'certificate'      => 'SHM',
                'year_built'       => null,
                'electric_power'   => null,
                'address'          => 'Berbah, Sleman',
                'latitude'         => -7.7500, 'longitude' => 110.4167,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[3]->id,
                'category_id'      => $catLand?->id,
                'property_type_id' => $typeTanah?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $berbah?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                'facilities'       => ['IMB', 'Akses Jalan Lebar', 'Listrik PLN'],
                'images'           => [
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                    'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
                    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
                    'https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=800&q=80',
                ],
            ],

            // ─── Apartemen disewa di Sleman ────────────────────────────────────
            [
                'title'            => 'Studio Apartment Condoview Sleman',
                'slug'             => 'studio-apartment-condoview-sleman',
                'property_id_code' => 'PROP-D23',
                'description'      => 'Studio apartment fully furnished di Condoview Sleman. Cocok untuk mahasiswa atau ekspat. Fasilitas lengkap, dekat kampus.',
                'short_description'=> 'Studio apartment furnished, dekat kampus di Sleman.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 2500000,
                'land_area'        => null, 'building_area' => 30,
                'bedrooms'         => 1,   'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHMSRS',
                'year_built'       => 2021,
                'electric_power'   => '1300W',
                'address'          => 'Condoview, Sleman',
                'latitude'         => -7.7550, 'longitude' => 110.3950,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[3]->id,
                'category_id'      => $catApt?->id,
                'property_type_id' => $typeApt?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $sleman?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                'facilities'       => ['Full Furnished', 'AC', 'Kolam Renang', 'Gym', 'WiFi', 'Lift'],
                'images'           => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80',
                    'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
                    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
                ],
            ],

            // ─── Rumah di Kota Yogyakarta (sold) ───────────────────────────────
            [
                'title'            => 'Rumah Heritage Kotagede',
                'slug'             => 'rumah-heritage-kotagede',
                'property_id_code' => 'PROP-D24',
                'description'      => 'Rumah bersejarah bergaya Heritage di Kotagede. Sudah terjual. Arsitektur kolonial dengan sentuhan tradisional Jawa.',
                'short_description'=> 'Rumah heritage Kotagede, arsitektur kolonial.',
                'transaction_type' => 'dijual',
                'price'            => 3500000000,
                'land_area'        => 200, 'building_area' => 150,
                'bedrooms'         => 3,   'bathrooms' => 2, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 1960,
                'electric_power'   => '1300W',
                'address'          => 'Kotagede, Kota Yogyakarta',
                'latitude'         => -7.8167, 'longitude' => 110.4000,
                'status'           => 'sold', 'is_featured' => false,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                'facilities'       => ['Arsitektur Heritage', 'Taman', 'Kolam Ikan', 'Pendopo'],
                'images'           => [
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566753376-12c8ab7c5a38?w=800&q=80',
                    'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&q=80',
                ],
            ],

            // ─── Ruko di Sleman (rented) ───────────────────────────────────────
            [
                'title'            => 'Ruko Sudah Disewa Prambanan',
                'slug'             => 'ruko-sudah-disewa-prambanan',
                'property_id_code' => 'PROP-D25',
                'description'      => 'Ruko di kawasan Prambanan yang sudah disewa. Listing ini untuk referensi sewa komersial.',
                'short_description'=> 'Ruko disewa di Prambanan, referensi komersial.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 6000000,
                'land_area'        => 60, 'building_area' => 90,
                'bedrooms'         => null, 'bathrooms' => 1, 'garage' => null, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2016,
                'electric_power'   => '3500W',
                'address'          => 'Prambanan, Sleman',
                'latitude'         => -7.7500, 'longitude' => 110.4500,
                'status'           => 'rented', 'is_featured' => false,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeRuko?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $prambanan?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                'facilities'       => ['Listrik 3 Phase', 'Air PDAM', 'Parkir'],
                'images'           => [
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&q=80',
                ],
            ],

            // ─── PROP-D26: Apartemen Dijual di Sleman ─────────────────────────
            [
                'title'            => 'Apartemen Premium Seturan',
                'slug'             => 'apartemen-premium-seturan',
                'property_id_code' => 'PROP-D26',
                'description'      => 'Apartemen premium 2 bedroom di Seturan, dekat UPN dan UIN. Fasilitas modern: kolam renang, gym, coworking space. Investasi cocok untuk mahasiswa.',
                'short_description'=> 'Apartemen 2BR premium dekat kampus, investasi menguntungkan.',
                'transaction_type' => 'dijual',
                'price'            => 850000000,
                'land_area'        => null, 'building_area' => 54,
                'bedrooms'         => 2,   'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHMSRS',
                'year_built'       => 2023,
                'electric_power'   => '2200W',
                'address'          => 'Seturan, Depok, Sleman',
                'latitude'         => -7.7580, 'longitude' => 110.3920,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[3]->id,
                'category_id'      => $catApt?->id,
                'property_type_id' => $typeApt?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $depok?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
                'facilities'       => ['Kolam Renang', 'Gym', 'Co-Working Space', 'Security 24 Jam', 'Lift', 'WiFi'],
                'images'           => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                    'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
                    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
                ],
            ],

            // ─── PROP-D27: Villa Dijual di Sleman ────────────────────────────
            [
                'title'            => 'Vila Mewah Kaliurang Private Pool',
                'slug'             => 'vila-mewah-kaliurang-private-pool',
                'property_id_code' => 'PROP-D27',
                'description'      => 'Vila mewah di kaki Gunung Merapi, Kaliurang. Private pool, taman tropis, gazebo. Lingkungan sejuk dan asri, cocok untuk liburan keluarga atau investasi homestay.',
                'short_description'=> 'Vila mewah private pool di Kaliurang, view Merapi.',
                'transaction_type' => 'dijual',
                'price'            => 8500000000,
                'land_area'        => 500, 'building_area' => 350,
                'bedrooms'         => 4,   'bathrooms' => 3, 'garage' => 2, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2022,
                'electric_power'   => '5500W',
                'address'          => 'Kaliurang, Pakem, Sleman',
                'latitude'         => -7.6800, 'longitude' => 110.4080,
                'status'           => 'published', 'is_featured' => true,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catVilla?->id,
                'property_type_id' => $typeVilla?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
                'facilities'       => ['Private Pool', 'View Merapi', 'Taman Tropis', 'Gazebo', 'BBQ Area', 'WiFi', 'Smart Home'],
                'images'           => [
                    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
                    'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
                    'https://images.unsplash.com/photo-1591825729269-caeb344f6df2?w=800&q=80',
                ],
            ],

            // ─── PROP-D28: Kantor Dijual di Bantul ───────────────────────────
            [
                'title'            => 'Gedung Kantor Siap Pakai Bantul',
                'slug'             => 'gedung-kantor-siap-pakai-bantul',
                'property_id_code' => 'PROP-D28',
                'description'      => 'Gedung kantor 3 lantai di jalan utama Bantul. Cocok untuk kantor perusahaan, klinik, atau institusi pendidikan. Fasilitas lengkap, parkir luas.',
                'short_description'=> 'Gedung kantor 3 lantai di jalan utama Bantul.',
                'transaction_type' => 'dijual',
                'price'            => 4200000000,
                'land_area'        => 300, 'building_area' => 450,
                'bedrooms'         => null, 'bathrooms' => 6, 'garage' => 10, 'floors' => 3,
                'certificate'      => 'SHM',
                'year_built'       => 2019,
                'electric_power'   => '10000W',
                'address'          => 'Jl. Bantul, Kasihan, Bantul',
                'latitude'         => -7.8750, 'longitude' => 110.3500,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catOffice?->id,
                'property_type_id' => $typeKantor?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $kasihan?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                'facilities'       => ['Listrik 10000W', 'AC Central', 'Ruang Rapat', 'Lift', 'Parkir Luas', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                    'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
                    'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&q=80',
                    'https://images.unsplash.com/photo-1497215842964-222b430dc094?w=800&q=80',
                ],
            ],

            // ─── PROP-D29: Hotel Disewa di Kota Yogyakarta ───────────────────
            [
                'title'            => 'Hotel Syariah Tugu Jogja',
                'slug'             => 'hotel-syariah-tugu-jogja',
                'property_id_code' => 'PROP-D29',
                'description'      => 'Hotel syariah 30 kamar di dekat Tugu Jogja. Sewa bulanan untuk operasional hotel. Lokasi premium, dekat Malioboro dan kraton.',
                'short_description'=> 'Hotel syariah 30 kamar dekat Tugu, sewa bulanan.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 35000000,
                'land_area'        => 500, 'building_area' => 800,
                'bedrooms'         => 30,  'bathrooms' => 32, 'garage' => 8, 'floors' => 3,
                'certificate'      => 'SHM',
                'year_built'       => 2018,
                'electric_power'   => '15000W',
                'address'          => 'Jl. Mangkubumen, Gondokusuman, Kota Yogyakarta',
                'latitude'         => -7.7950, 'longitude' => 110.3640,
                'status'           => 'published', 'is_featured' => true,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeHotel?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => $gondokusuman?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
                'facilities'       => ['Kolam Renang', 'Restoran', 'Ruang Meeting', 'WiFi', 'Laundry', 'Mushola'],
                'images'           => [
                    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
                    'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
                    'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
                ],
            ],

            // ─── PROP-D30: Tanah Disewa di Kulon Progo ───────────────────────
            [
                'title'            => 'Tanah Sawah Sewa Tahunan Galur',
                'slug'             => 'tanah-sawah-sewa-tahunan-galur',
                'property_id_code' => 'PROP-D30',
                'description'      => 'Tanah sawah seluas 2000m² untuk disewa tahunan di Galur, Kulon Progo. Produktif untuk tanaman padi dan palawija. Air irigasi tersedia.',
                'short_description'=> 'Tanah sawah 2000m² sewa tahunan di Galur, produktif.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 4000000,
                'land_area'        => 2000, 'building_area' => null,
                'bedrooms'         => null, 'bathrooms' => null, 'garage' => null, 'floors' => null,
                'certificate'      => null,
                'year_built'       => null,
                'electric_power'   => null,
                'address'          => 'Galur, Kulon Progo',
                'latitude'         => -7.7833, 'longitude' => 110.2000,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[4]->id,
                'category_id'      => $catLand?->id,
                'property_type_id' => $typeTanah?->id,
                'city_id'          => $klp?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                'facilities'       => ['Air Irigasi', 'Jalan Traktor', 'Tanah Subur', 'Produktif'],
                'images'           => [
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                    'https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=800&q=80',
                    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
                    'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
                ],
            ],

            // ─── PROP-D31: Ruko Dijual di Kota Yogyakarta ────────────────────
            [
                'title'            => 'Ruko 3 Lantai Jalan Malioboro',
                'slug'             => 'ruko-3-lantai-jalan-malioboro',
                'property_id_code' => 'PROP-D31',
                'description'      => 'Ruko strategis 3 lantai di kawasan Malioboro. Cocok untuk restoran, hotel, atau toko souvenir. Nilai investasi tinggi, lalu lintas pejalan kaki sangat ramai.',
                'short_description'=> 'Ruko 3 lantai di Malioboro, investasi premium.',
                'transaction_type' => 'dijual',
                'price'            => 7500000000,
                'land_area'        => 100, 'building_area' => 250,
                'bedrooms'         => null, 'bathrooms' => 4, 'garage' => null, 'floors' => 3,
                'certificate'      => 'SHM',
                'year_built'       => 2015,
                'electric_power'   => '5500W',
                'address'          => 'Jl. Malioboro, Gondokusuman, Kota Yogyakarta',
                'latitude'         => -7.7920, 'longitude' => 110.3660,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeRuko?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => $gondokusuman?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                'facilities'       => ['Listrik 5500W', 'Air PDAM', 'Ruang Display', 'Gudang', 'Akses Pejalan Kaki'],
                'images'           => [
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
                ],
            ],

            // ─── PROP-D32: Gudang Dijual di Kota Yogyakarta ──────────────────
            [
                'title'            => 'Gudang Industrial Umbulharjo',
                'slug'             => 'gudang-industrial-umbulharjo',
                'property_id_code' => 'PROP-D32',
                'description'      => 'Gudang industrial siap pakai di Umbulharjo, Kota Yogyakarta. Luas 400m², lantai beton, listrik 5500W. Dekat akses jalan raya, cocok untuk distribusi.',
                'short_description'=> 'Gudang 400m² di Umbulharjo, akses jalan raya.',
                'transaction_type' => 'dijual',
                'price'            => 3200000000,
                'land_area'        => 500, 'building_area' => 400,
                'bedrooms'         => null, 'bathrooms' => 2, 'garage' => null, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2016,
                'electric_power'   => '5500W',
                'address'          => 'Umbulharjo, Kota Yogyakarta',
                'latitude'         => -7.8080, 'longitude' => 110.3560,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeGudang?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => $umbulharjo?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                'facilities'       => ['Listrik 5500W', 'Lantai Beton', 'Akses Truk', 'Parkir Luas', 'Keamanan'],
                'images'           => [
                    'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                    'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
                    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
                    'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80',
                ],
            ],

            // ─── PROP-D33: Rumah di Sleman (disewa) ──────────────────────────
            [
                'title'            => 'Rumah Mewah Sewa Bulanan Godean',
                'slug'             => 'rumah-mewah-sewa-bulanan-godean',
                'property_id_code' => 'PROP-D33',
                'description'      => 'Rumah mewah 3 lantai untuk disewa bulanan di Godean, Sleman. Full furnished, kolam renang, taman luas. Cocok untuk expatriat atau keluarga besar.',
                'short_description'=> 'Rumah mewah 3 lantai sewa bulanan di Godean, full furnished.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 25000000,
                'land_area'        => 350, 'building_area' => 300,
                'bedrooms'         => 4,   'bathrooms' => 3, 'garage' => 2, 'floors' => 3,
                'certificate'      => 'SHM',
                'year_built'       => 2021,
                'electric_power'   => '5500W',
                'address'          => 'Godean, Sleman',
                'latitude'         => -7.7667, 'longitude' => 110.3500,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $godean?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
                'facilities'       => ['Full Furnished', 'Kolam Renang', 'Taman Luas', 'Garasi 2 Mobil', 'Smart Home', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566753376-12c8ab7c5a38?w=800&q=80',
                ],
            ],

            // ─── PROP-D34: Apartemen Disewa di Kota Yogyakarta ───────────────
            [
                'title'            => 'Apartemen Cozy Tegalrejo Jogja',
                'slug'             => 'apartemen-cozy-tegalrejo-jogja',
                'property_id_code' => 'PROP-D34',
                'description'      => 'Apartemen cozie studio di Tegalrejo, Kota Yogyakarta. Fully furnished, dekat kampus UNY dan UMY. Cocok untuk mahasiswa atau pekerja muda.',
                'short_description'=> 'Apartemen studio furnished dekat UNY & UMY.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 3000000,
                'land_area'        => null, 'building_area' => 36,
                'bedrooms'         => 1,   'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHMSRS',
                'year_built'       => 2020,
                'electric_power'   => '1300W',
                'address'          => 'Tegalrejo, Kota Yogyakarta',
                'latitude'         => -7.7830, 'longitude' => 110.3700,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catApt?->id,
                'property_type_id' => $typeApt?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                'facilities'       => ['Full Furnished', 'AC', 'WiFi', 'Security', 'Lift', 'Laundry'],
                'images'           => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&q=80',
                    'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
                    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
                ],
            ],

            // ─── PROP-D35: Tanah Dijual di Gunungkidul ───────────────────────
            [
                'title'            => 'Tanah Kebun Produktif Ngawen',
                'slug'             => 'tanah-kebun-produktif-ngawen',
                'property_id_code' => 'PROP-D35',
                'description'      => 'Tanah kebun seluas 1500m² di Ngawen, Gunungkidul. Sudah ada tanaman buah-buahan (durian, mangga, jambu). Cocok untuk agrowisata atau kebun organik.',
                'short_description'=> 'Tanah kebun 1500m² dengan tanaman buah di Ngawen.',
                'transaction_type' => 'dijual',
                'price'            => 375000000,
                'land_area'        => 1500, 'building_area' => null,
                'bedrooms'         => null, 'bathrooms' => null, 'garage' => null, 'floors' => null,
                'certificate'      => 'SHM',
                'year_built'       => null,
                'electric_power'   => null,
                'address'          => 'Ngawen, Gunungkidul',
                'latitude'         => -7.9333, 'longitude' => 110.6500,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catLand?->id,
                'property_type_id' => $typeTanah?->id,
                'city_id'          => $gk?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                'facilities'       => ['Tanaman Buah', 'Air Sumur', 'Akses Jalan', 'View Alam'],
                'images'           => [
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                    'https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=800&q=80',
                    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
                    'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
                ],
            ],

            // ─── PROP-D36: Ruko Disewa di Bantul ─────────────────────────────
            [
                'title'            => 'Ruko Modern Sewa Bulanan Sewon',
                'slug'             => 'ruko-modern-sewa-bulanan-sewon',
                'property_id_code' => 'PROP-D36',
                'description'      => 'Ruko modern 2 lantai untuk disewa bulanan di Sewon, Bantul. Lokasi dekat UIN Sunan Kalijaga. Cocok untuk kafe, toko buku, atau kantor kreatif.',
                'short_description'=> 'Ruko modern sewa bulanan dekat UIN, kawasan kreatif.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 10000000,
                'land_area'        => 90, 'building_area' => 140,
                'bedrooms'         => null, 'bathrooms' => 2, 'garage' => 1, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2022,
                'electric_power'   => '3500W',
                'address'          => 'Sewon, Bantul',
                'latitude'         => -7.8250, 'longitude' => 110.3600,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeRuko?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => $seweon?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                'facilities'       => ['Listrik 3500W', 'Air PDAM', 'Ruang Display', 'Dapur', 'WiFi'],
                'images'           => [
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
                ],
            ],

            // ─── PROP-D37: Hotel Dijual di Bantul ────────────────────────────
            [
                'title'            => 'Homestay Pantai Parangtritis',
                'slug'             => 'homestay-pantai-parangtritis',
                'property_id_code' => 'PROP-D37',
                'description'      => 'Homestay 10 kamar di dekat Pantai Parangtritis, Bantul. Setiap kamar AC dan kamar mandi dalam. Cocok untuk investasi wisata pantai selatan.',
                'short_description'=> 'Homestay 10 kamar dekat Parangtritis, investasi wisata.',
                'transaction_type' => 'dijual',
                'price'            => 2500000000,
                'land_area'        => 400, 'building_area' => 350,
                'bedrooms'         => 10,  'bathrooms' => 10, 'garage' => 3, 'floors' => 2,
                'certificate'      => 'SHM',
                'year_built'       => 2017,
                'electric_power'   => '5500W',
                'address'          => 'Parangtritis, Kretek, Bantul',
                'latitude'         => -8.0250, 'longitude' => 110.3300,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeHotel?->id,
                'city_id'          => $bantul?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
                'facilities'       => ['AC', 'Kamar Mandi Dalam', 'Taman', 'Parkir', 'Dapur Bersama', 'WiFi'],
                'images'           => [
                    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
                    'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
                    'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
                ],
            ],

            // ─── PROP-D38: Kantor Disewa di Kota Yogyakarta ──────────────────
            [
                'title'            => 'Virtual Office Premium Jetis',
                'slug'             => 'virtual-office-premium-jetis',
                'property_id_code' => 'PROP-D38',
                'description'      => 'Virtual office premium di Jetis, Kota Yogyakarta. Tersedia layanan resepsionis, ruang rapat sharing, dan alamat bisnis resmi. Cocok untuk startup dan UMKM.',
                'short_description'=> 'Virtual office premium di Jetis, layanan lengkap.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 1500000,
                'land_area'        => null, 'building_area' => 15,
                'bedrooms'         => null, 'bathrooms' => 1, 'garage' => null, 'floors' => 1,
                'certificate'      => null,
                'year_built'       => 2023,
                'electric_power'   => '1300W',
                'address'          => 'Jetis, Kota Yogyakarta',
                'latitude'         => -7.7880, 'longitude' => 110.3680,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[1]->id,
                'category_id'      => $catOffice?->id,
                'property_type_id' => $typeKantor?->id,
                'city_id'          => $jogja?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                'facilities'       => ['Resepsionis', 'Ruang Rapat Sharing', 'WiFi', 'Printer', 'Scan & Fotokopi', 'Alamat Bisnis'],
                'images'           => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                    'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&q=80',
                    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
                    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&q=80',
                ],
            ],

            // ─── PROP-D39: Rumah Dijual di Kulon Progo ───────────────────────
            [
                'title'            => 'Rumah Tradisional Jawa Nanggulan',
                'slug'             => 'rumah-tradisional-jawa-nanggulan',
                'property_id_code' => 'PROP-D39',
                'description'      => 'Rumah tradisional Jawa di Nanggulan, Kulon Progo. Arsitektur joglo dengan pendopo, taman belakang luas. Suasana pedesaan yang autentik.',
                'short_description'=> 'Rumah joglo di Nanggulan, suasana pedesaan autentik.',
                'transaction_type' => 'dijual',
                'price'            => 1800000000,
                'land_area'        => 400, 'building_area' => 200,
                'bedrooms'         => 3,   'bathrooms' => 2, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2001,
                'electric_power'   => '2200W',
                'address'          => 'Nanggulan, Kulon Progo',
                'latitude'         => -7.8000, 'longitude' => 110.2200,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[4]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $klp?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                'facilities'       => ['Pendopo', 'Taman Belakang', 'Sumur Bor', 'Dapur Tradisional', 'Garasi'],
                'images'           => [
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80',
                    'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&q=80',
                ],
            ],

            // ─── PROP-D40: Gudang Disewa di Sleman ───────────────────────────
            [
                'title'            => 'Gudang Logistik Dekat Jalan Tol Sleman',
                'slug'             => 'gudang-logistik-dekat-jalan-tol-sleman',
                'property_id_code' => 'PROP-D40',
                'description'      => 'Gudang logistik seluas 800m² dekat akses jalan tol Sleman. Sangat cocok untuk pusat distribusi, e-commerce fulfillment, atau cold storage.',
                'short_description'=> 'Gudang 800m² dekat tol Sleman, cocok logistik.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 25000000,
                'land_area'        => 1000, 'building_area' => 800,
                'bedrooms'         => null, 'bathrooms' => 2, 'garage' => null, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2021,
                'electric_power'   => '10000W',
                'address'          => 'Ngemplak, Sleman',
                'latitude'         => -7.7400, 'longitude' => 110.4050,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeGudang?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => null,
                'thumbnail'        => 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                'facilities'       => ['Listrik 10000W', 'Akses Tol', 'Loading Dock', 'Parkir Truk', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=800&q=80',
                    'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
                    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
                    'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80',
                ],
            ],

            // ─── PROP-D41: Ruko Disewa di Gunungkidul ────────────────────────
            [
                'title'            => 'Ruko Strategis Sewa Bulanan Wonosari',
                'slug'             => 'ruko-strategis-sewa-bulanan-wonosari',
                'property_id_code' => 'PROP-D41',
                'description'      => 'Ruko 1 lantai strategis untuk disewa bulanan di Wonosari, Gunungkidul. Cocok untuk minimarket, apotek, atau warung makan. Lokasi ramai penduduk.',
                'short_description'=> 'Ruko 1 lantai sewa bulanan, lokasi ramai Wonosari.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 5000000,
                'land_area'        => 60, 'building_area' => 80,
                'bedrooms'         => null, 'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2019,
                'electric_power'   => '2200W',
                'address'          => 'Wonosari, Gunungkidul',
                'latitude'         => -7.9650, 'longitude' => 110.6020,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeRuko?->id,
                'city_id'          => $gk?->id,
                'district_id'      => $wonosari?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                'facilities'       => ['Listrik 2200W', 'Air PDAM', 'Ruang Display', 'Gudang Kecil'],
                'images'           => [
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
                ],
            ],

            // ─── PROP-D42: Rumah Dijual di Gunungkidul ───────────────────────
            [
                'title'            => 'Rumah Minimalis Asri Wonosari',
                'slug'             => 'rumah-minimalis-asri-wonosari',
                'property_id_code' => 'PROP-D42',
                'description'      => 'Rumah minimalis modern di Wonosari, Gunungkidul. Lingkungan perumahan baru, dekat pasar dan sekolah. Harga terjangkau untuk keluarga muda.',
                'short_description'=> 'Rumah minimalis modern di Wonosari, harga terjangkau.',
                'transaction_type' => 'dijual',
                'price'            => 550000000,
                'land_area'        => 90, 'building_area' => 60,
                'bedrooms'         => 2,   'bathrooms' => 1, 'garage' => 1, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2024,
                'electric_power'   => '1300W',
                'address'          => 'Wonosari, Gunungkidul',
                'latitude'         => -7.9680, 'longitude' => 110.5980,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[2]->id,
                'category_id'      => $catRes?->id,
                'property_type_id' => $typeRumah?->id,
                'city_id'          => $gk?->id,
                'district_id'      => $wonosari?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
                'facilities'       => ['Carport', 'Taman', 'Air PDAM', 'One Gate System', 'CCTV'],
                'images'           => [
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
                    'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
                    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&q=80',
                ],
            ],

            // ─── PROP-D43: Commercial Disewa di Sleman ───────────────────────
            [
                'title'            => 'Food Court & Space Sewa Bulanan Sleman',
                'slug'             => 'food-court-space-sewa-bulanan-sleman',
                'property_id_code' => 'PROP-D43',
                'description'      => 'Space food court 200m² untuk disewa bulanan di kawasan wisata Sleman. Sudah ada 5 booth, tempat duduk outdoor. Cocok untuk kuliner atau co-working cafe.',
                'short_description'=> 'Space food court 200m² sewa bulanan, siap operasional.',
                'transaction_type' => 'disewa',
                'price'            => null,
                'price_rent_monthly' => 15000000,
                'land_area'        => 250, 'building_area' => 200,
                'bedrooms'         => null, 'bathrooms' => 3, 'garage' => 5, 'floors' => 1,
                'certificate'      => 'SHM',
                'year_built'       => 2023,
                'electric_power'   => '7700W',
                'address'          => 'Mlati, Sleman',
                'latitude'         => -7.7500, 'longitude' => 110.3800,
                'status'           => 'published', 'is_featured' => false,
                'agent_id'         => $agents[0]->id,
                'category_id'      => $catCom?->id,
                'property_type_id' => $typeCom?->id,
                'city_id'          => $sleman?->id,
                'district_id'      => $mlati?->id,
                'thumbnail'        => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                'facilities'       => ['5 Booth', 'Tempat Duduk Outdoor', 'Listrik 7700W', 'Dapur Umum', 'Area Parkir', 'WiFi'],
                'images'           => [
                    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
                    'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
                    'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
                ],
            ],
        ];

        foreach ($properties as $propertyData) {
            $facilities = $propertyData['facilities'] ?? [];
            $images     = $propertyData['images'] ?? [];
            unset($propertyData['facilities'], $propertyData['images']);

            $propertyData['province_id'] = 1;
            $propertyData['published_at'] = $propertyData['status'] === 'draft' ? null : now()->subDays(rand(1, 60));

            $property = Property::create($propertyData);

            foreach ($facilities as $facility) {
                PropertyFacility::create([
                    'property_id' => $property->id,
                    'name'        => $facility,
                    'icon'        => 'fa-check',
                ]);
            }

            foreach ($images as $i => $imageUrl) {
                PropertyImage::create([
                    'property_id' => $property->id,
                    'image_url'   => $imageUrl,
                    'alt_text'    => $property->title,
                    'sort_order'  => $i,
                    'is_primary'  => $i === 0,
                ]);
            }
        }

        $this->command->info('Dummy properties seeded successfully! Total: ' . count($properties) . ' properties.');
    }
}
