/* DJM — Desty Jaya Mandiri | Data statis */
const DJM = {
  name: "DJM",
  fullName: "Desty Jaya Mandiri",
  tagline: "Solusi Properti, Perizinan & Konstruksi Terpercaya",
  area: "Yogyakarta dan sekitarnya",
  address: "Jl. Kaliurang KM 7, Sleman, Yogyakarta",
  phone: "+62 274 123456",
  phoneRaw: "+62274123456",
  wa: "6281234567890",
  email: "info@djmproperty.id",
  hours: "Senin – Jumat: 08.00–17.00 WIB",
  instagram: "#",
  facebook: "#",
  experience: "15+",
  stats: [
    { value: "2000+", label: "Properti Terdaftar" },
    { value: "1500+", label: "Klien Puas" },
    { value: "15+", label: "Tahun Pengalaman" },
  ],

  categories: {
    perizinan: "Perizinan",
    konstruksi: "Konstruksi",
  },

  services: [
    {
      slug: "pbg-imb",
      name: "PBG / IMB",
      category: "perizinan",
      icon: "fa-solid fa-file-signature",
      short:
        "Pengurusan Persetujuan Bangunan Gedung (PBG) dan Izin Mendirikan Bangunan (IMB) secara cepat, resmi, dan terpercaya.",
      desc: [
        "PBG (Persetujuan Bangunan Gedung) dan IMB (Izin Mendirikan Bangunan) adalah legalitas wajib untuk membangun, merenovasi, atau memanfaatkan bangunan gedung.",
        "DJM membantu Anda mengurus perizinan bangunan dengan dokumen yang lengkap dan proses yang transparan, sehingga bangunan Anda aman dan sesuai ketentuan yang berlaku.",
      ],
      scope: [
        "Pengurusan PBG baru untuk bangunan rumah tinggal maupun komersial",
        "Pengurusan IMB untuk bangunan yang belum berizin",
        "Persiapan dan verifikasi kelengkapan dokumen teknis",
        "Pendampingan hingga izin terbit",
      ],
      process: [
        "Konsultasi awal dan identifikasi kebutuhan izin",
        "Pemeriksaan kelengkapan dokumen",
        "Pengajuan dan pengurusan ke instansi terkait",
        "Izin terbit & penyerahan dokumen",
      ],
    },
    {
      slug: "pengeringan",
      name: "Pengeringan",
      category: "perizinan",
      icon: "fa-solid fa-water",
      short:
        "Jasa pengeringan lahan untuk menyiapkan tanah yang layak dan siap dibangun.",
      desc: [
        "Lahan yang tergenang atau memiliki kadar air tinggi tidak ideal untuk dibangun. DJM membantu proses pengeringan lahan agar tanah menjadi stabil dan siap digunakan.",
        "Proses dikerjakan sesuai kondisi lahan dan kebutuhan, dengan hasil yang maksimal untuk mendukung pembangunan Anda.",
      ],
      scope: [
        "Analisis kondisi lahan dan tingkat genangan",
        "Perencanaan sistem pengeringan yang sesuai",
        "Pelaksanaan pengeringan lahan",
        "Pengecekan kesiapan lahan sebelum dibangun",
      ],
      process: [
        "Survei dan penilaian kondisi lahan",
        "Usulan metode pengeringan",
        "Pelaksanaan pekerjaan pengeringan",
        "Laporan hasil & serah terima",
      ],
    },
    {
      slug: "pecah-sertifikat",
      name: "Pecah Sertifikat",
      category: "perizinan",
      icon: "fa-solid fa-file-invoice",
      short:
        "Pemecahan sertifikat tanah sesuai kebutuhan legal dan peruntukan lahan Anda.",
      desc: [
        "Pecah sertifikat diperlukan ketika sebidang tanah akan dibagi menjadi beberapa bagian, baik untuk penjualan, warisan, maupun peruntukan lain.",
        "DJM mengurus proses pemecahan sertifikat secara resmi dengan dokumen yang lengkap dan proses yang terpantau.",
      ],
      scope: [
        "Pemecahan sertifikat tanah sesuai rencana pembagian",
        "Pengurusan dokumen ke instansi terkait",
        "Pendampingan hingga sertifikat pecah terbit",
      ],
      process: [
        "Konsultasi kebutuhan dan rencana pembagian",
        "Pengumpulan & verifikasi dokumen tanah",
        "Pengajuan pemecahan sertifikat",
        "Sertifikat pecah terbit & serah terima",
      ],
    },
    {
      slug: "pembangunan",
      name: "Pembangunan",
      category: "konstruksi",
      icon: "fa-solid fa-building-construction",
      short:
        "Jasa pembangunan bangunan dari fondasi hingga selesai oleh tim berpengalaman.",
      desc: [
        "DJM melayani pembangunan rumah, ruko, dan bangunan lainnya secara menyeluruh — dari perencanaan, konstruksi, hingga bangunan siap digunakan.",
        "Pengerjaan dilakukan oleh tim berpengalaman dengan material terpilih dan pengawasan yang ketat di setiap tahap.",
      ],
      scope: [
        "Pembangunan rumah tinggal",
        "Pembangunan ruko dan bangunan komersial",
        "Pekerjaan struktur, arsitektur, dan utilitas",
        "Pengawasan proyek hingga selesai",
      ],
      process: [
        "Konsultasi kebutuhan & survey lokasi",
        "Perencanaan dan estimasi biaya",
        "Pelaksanaan pembangunan",
        "Serah terima bangunan",
      ],
    },
    {
      slug: "renovasi",
      name: "Renovasi",
      category: "konstruksi",
      icon: "fa-solid fa-hammer",
      short:
        "Renovasi dan perbaikan bangunan untuk meningkatkan kenyamanan dan nilai properti.",
      desc: [
        "Bangunan yang sudah berumur atau ingin diubah tata ruangnya bisa direnovasi oleh DJM. Kami menangani renovasi total maupun parsial sesuai kebutuhan.",
        "Hasil renovasi dirancang untuk meningkatkan kenyamanan, fungsi, dan nilai properti Anda.",
      ],
      scope: [
        "Renovasi total maupun sebagian",
        "Perombakan tata ruang (layout)",
        "Perbaikan struktur dan finishing",
        "Pembaruan utilitas bangunan",
      ],
      process: [
        "Inspeksi kondisi bangunan",
        "Perencanaan renovasi & RAB",
        "Pelaksanaan renovasi",
        "Serah terima hasil renovasi",
      ],
    },
    {
      slug: "jasa-konstruksi",
      name: "Jasa Konstruksi",
      category: "konstruksi",
      icon: "fa-solid fa-helmet-safety",
      short:
        "Layanan konstruksi umum untuk berbagai kebutuhan pembangunan Anda.",
      desc: [
        "DJM menyediakan jasa konstruksi umum yang mencakup berbagai pekerjaan pembangunan dan perawatan bangunan.",
        "Tim kami siap membantu mewujudkan kebutuhan konstruksi Anda dengan kualitas dan ketepatan waktu.",
      ],
      scope: [
        "Konstruksi umum dan pekerjaan sipil",
        "Perawatan dan perbaikan bangunan",
        "Pekerjaan tambahan sesuai kebutuhan proyek",
      ],
      process: [
        "Konsultasi kebutuhan konstruksi",
        "Penawaran & kesepakatan lingkup kerja",
        "Pelaksanaan pekerjaan",
        "Serah terima & perawatan lanjutan",
      ],
    },
  ],

  properties: [
    {
      slug: "rumah-minimalis-sleman",
      title: "Rumah Minimalis Sleman",
      status: "dijual",
      featured: true,
      type: "Rumah",
      price: "Rp750.000.000",
      location: "Sleman, Yogyakarta",
      land: "120 m\u00b2",
      building: "90 m\u00b2",
      bedrooms: "3",
      bathrooms: "2",
      facilities: ["Garasi", "Listrik 2200W", "Air PAM", "Semi Furnished"],
      short:
        "Rumah minimalis 2 lantai di kawasan strategis Sleman, dekat fasilitas pendidikan dan perkantoran.",
      desc: "Rumah minimalis dengan desain modern di Sleman. Lokasi strategis dekat kampus, pasar, dan akses ring road. Cocok untuk tempat tinggal maupun investasi.",
    },
    {
      slug: "tanah-kavling-kaliurang",
      title: "Tanah Kavling Kaliurang",
      status: "dijual",
      featured: true,
      type: "Tanah",
      price: "Rp450.000.000",
      location: "Kaliurang, Sleman",
      land: "250 m\u00b2",
      building: "-",
      bedrooms: "-",
      bathrooms: "-",
      facilities: ["Akses jalan mobil", "Sertifikat SHM", "Lingkungan asri"],
      short: "Kavling tanah siap bangun di kawasan dingin Kaliurang dengan pemandangan alam.",
      desc: "Tanah kavling strategis di Kaliurang, cocok untuk rumah liburan atau investasi lahan. Lingkungan asri dan akses mudah.",
    },
    {
      slug: "ruko-ringroad-utara",
      title: "Ruko 2 Lantai Ringroad Utara",
      status: "disewakan",
      featured: true,
      type: "Ruko",
      price: "Rp35.000.000/tahun",
      location: "Ringroad Utara, Sleman",
      land: "72 m\u00b2",
      building: "144 m\u00b2",
      bedrooms: "-",
      bathrooms: "2",
      facilities: ["2 lantai", "Shoplot", "Parkir luas", "Listrik 4400W"],
      short: "Ruko 2 lantai di tepi Ringroad Utara, sangat strategis untuk usaha.",
      desc: "Ruko di lokasi prime ringroad utara. Sangat cocok untuk kantor, toko, kafe, atau jasa. Area parkir luas dan ramai lalu lintas.",
    },
    {
      slug: "villa-kaliurang",
      title: "Villa Kaliurang",
      status: "disewakan",
      featured: false,
      type: "Villa",
      price: "Rp5.000.000/bulan",
      location: "Kaliurang, Sleman",
      land: "300 m\u00b2",
      building: "120 m\u00b2",
      bedrooms: "2",
      bathrooms: "2",
      facilities: ["Taman", "Pemandangan gunung", "Furnished", "Dapur"],
      short: "Villa cozy di pegunungan Kaliurang, cocok untuk liburan keluarga.",
      desc: "Villa dengan pemandangan alam di Kaliurang. Dilengkapi perabotan, taman, dan suasana yang sejuk. Ideal untuk liburan atau staycation.",
    },
    {
      slug: "rumah-semi-depok",
      title: "Rumah Semi Depok",
      status: "dijual",
      featured: false,
      type: "Rumah",
      price: "Rp1.100.000.000",
      location: "Depok, Sleman",
      land: "150 m\u00b2",
      building: "130 m\u00b2",
      bedrooms: "4",
      bathrooms: "3",
      facilities: ["2 lantai", "Garasi 2 mobil", "Taman", "Sholat room"],
      short: "Rumah semi modern dekat kampus UGM dan akses ring road.",
      desc: "Rumah semi modern di Depok, dekat dengan kampus dan pusat aktivitas. Bangunan kokoh dengan kamar yang lega.",
    },
    {
      slug: "tanah-sleman-barat",
      title: "Tanah Sleman Barat",
      status: "dijual",
      featured: false,
      type: "Tanah",
      price: "Rp320.000.000",
      location: "Sleman Barat, Sleman",
      land: "400 m\u00b2",
      building: "-",
      bedrooms: "-",
      bathrooms: "-",
      facilities: ["Sertifikat SHM", "Harga murah", "Akses jalan"],
      short: "Tanah luas di Sleman barat dengan harga terjangkau, cocok untuk investasi.",
      desc: "Tanah luas dengan harga bersahabat di Sleman barat. Cocok untuk investasi jangka panjang atau membangun rumah masa depan.",
    },
  ],

  portfolios: [
    {
      slug: "pengurusan-pbg-perumahan",
      title: "Pengurusan PBG Perumahan Sleman",
      category: "perizinan",
      location: "Sleman, Yogyakarta",
      year: "2025",
      short: "Pengurusan PBG untuk satu kompleks perumahan di Sleman.",
      desc: "DJM mengurus PBG untuk puluhan unit rumah dalam satu kompleks perumahan di Sleman, dari pengumpulan dokumen hingga izin terbit.",
    },
    {
      slug: "pembangunan-rumah-2-lantai",
      title: "Pembangunan Rumah 2 Lantai Depok",
      category: "konstruksi",
      location: "Depok, Sleman",
      year: "2025",
      short: "Pembangunan rumah 2 lantai modern di Depok.",
      desc: "Proyek pembangunan rumah 2 lantai dengan konsep modern minimalis. Dikerjakan penuh oleh tim konstruksi DJM.",
    },
    {
      slug: "renovasi-ruko-kaliurang",
      title: "Renovasi Ruko Jl. Kaliurang",
      category: "konstruksi",
      location: "Kaliurang, Sleman",
      year: "2024",
      short: "Renovasi total ruko 2 lantai di Jl. Kaliurang.",
      desc: "Renovasi menyeluruh ruko 2 lantai termasuk perombakan layout dan perbaikan struktur.",
    },
    {
      slug: "pecah-sertifikat-kasihan",
      title: "Pecah Sertifikat Tanah Kasihan",
      category: "perizinan",
      location: "Kasihan, Bantul",
      year: "2024",
      short: "Pemecahan sertifikat tanah menjadi beberapa kavling.",
      desc: "Pengurusan pecah sertifikat sebidang tanah di Kasihan untuk rencana pembangunan beberapa unit rumah.",
    },
    {
      slug: "penjualan-rumah-minimalis",
      title: "Penjualan Rumah Minimalis Sleman",
      category: "property",
      location: "Sleman, Yogyakarta",
      year: "2024",
      short: "Proses jual beli rumah minimalis di Sleman.",
      desc: "Pendampingan proses jual beli rumah minimalis di Sleman mulai dari pemasaran hingga akad.",
    },
    {
      slug: "pembangunan-mushola",
      title: "Pembangunan Mushola Kompleks",
      category: "konstruksi",
      location: "Depok, Sleman",
      year: "2023",
      short: "Pembangunan mushola untuk kompleks perumahan.",
      desc: "Pembangunan mushola dengan kapasitas 100 jamaah untuk fasilitas ibadah kompleks perumahan.",
    },
  ],
};
